---
# tasks file for prometheus-postgres

- name: Ensure {{ prometheus_postgres_system_user }} users exists
  user:
    name: "{{ prometheus_postgres_system_user }}"
    comment: "prometheus_postgres_system_user"
    system: true
    shell: /bin/false
    create_home: false
  when: "prometheus_postgres_system_user != 'postgres'"

- name: prometheus postgres | create directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /opt/prometheus/postgres
    - /etc/prometheus

- name: prometheus postgres | download
  become: true
  get_url:
    # note the v0.9.0 in tag but 0.9.0 in the filename
    url: "https://github.com/prometheus-community/postgres_exporter/\
      releases/download/v{{ prometheus_postgres_version }}/\
      postgres_exporter-{{ prometheus_postgres_version }}.linux-amd64.tar.gz"
    checksum: sha256:{{ prometheus_postgres_sha256 }}
    dest: "/opt/prometheus/postgres_exporter\
      -{{ prometheus_postgres_version }}.linux-amd64.tar.gz"

- name: prometheus postgres | install postgres-exporter
  become: true
  unarchive:
    src: "/opt/prometheus/postgres_exporter\
      -{{ prometheus_postgres_version }}.linux-amd64.tar.gz"
    dest: /opt/prometheus
    group: root
    owner: root
    remote_src: true

- name: prometheus postgres | symlink postgres-exporter
  become: true
  file:
    src: "/opt/prometheus/postgres_exporter\
      -{{ prometheus_postgres_version }}.linux-amd64"
    path: /opt/prometheus/postgres_exporter
    force: true
    state: link
  notify:
    - restart prometheus-postgres

- name: prometheus postgres | configuration file
  become: true
  assemble:
    dest: /etc/prometheus/postgres-queries.yml
    regexp: "^{{ prometheus_postgres_query_filenames | join('|') }}$"
    remote_src: false
    src: "{{ prometheus_postgres_query_directory }}"
    mode: 0644
  notify:
    - restart prometheus-postgres

- name: prometheus postgres | web config
  become: true
  template:
    dest: /etc/prometheus/web-config.yml
    src: web-config.yml.j2
    mode: 0644
  notify:
    - restart prometheus-postgres

- name: prometheus postgres | server systemd service
  become: true
  template:
    dest: /etc/systemd/system/prometheus-postgres-exporter.service
    src: systemd-system-prometheus-postgres-exporter-service.j2
    mode: 0644
  notify:
    - restart prometheus-postgres

- name: prometheus postgres | enable and start server systemd
  become: true
  systemd:
    daemon_reload: true
    enabled: true
    name: prometheus-postgres-exporter.service
    state: started
